/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : string,
  'featuredImage' : [] | [ExternalBlob],
  'tags' : Array<string>,
  'author' : string,
}
export interface ContactSubmission {
  'id' : string,
  'subject' : string,
  'date' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Event {
  'id' : string,
  'title' : string,
  'date' : string,
  'time' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'school' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export interface PublicSiteSettings {
  'logo' : [] | [ExternalBlob],
  'heroBackground' : [] | [ExternalBlob],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteSettings {
  'logo' : [] | [ExternalBlob],
  'whatsappNumber' : string,
  'heroBackground' : [] | [ExternalBlob],
}
export interface Sponsor {
  'id' : string,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'description' : string,
  'website' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TeamMember {
  'id' : string,
  'bio' : string,
  'name' : string,
  'role' : string,
  'photo' : [] | [ExternalBlob],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'organization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'url' : string,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'description' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAboutSection' : ActorMethod<[AboutSection], undefined>,
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addContactSubmission' : ActorMethod<[ContactSubmission], undefined>,
  'addEvent' : ActorMethod<[Event], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addSponsor' : ActorMethod<[Sponsor], undefined>,
  'addTeamMember' : ActorMethod<[TeamMember], undefined>,
  'addVideo' : ActorMethod<[Video], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAboutSection' : ActorMethod<[string], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteContactSubmission' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteGalleryImage' : ActorMethod<[string], undefined>,
  'deleteSponsor' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllAboutSections' : ActorMethod<[], Array<AboutSection>>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getPublicSiteSettings' : ActorMethod<[], PublicSiteSettings>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getSponsors' : ActorMethod<[], Array<Sponsor>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'getWhatsAppLink' : ActorMethod<[], string>,
  'isAdminConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminCredentials' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAboutSection' : ActorMethod<[AboutSection], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateEvent' : ActorMethod<[Event], undefined>,
  'updateGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'updateSponsor' : ActorMethod<[Sponsor], undefined>,
  'updateTeamMember' : ActorMethod<[TeamMember], undefined>,
  'updateVideo' : ActorMethod<[Video], undefined>,
  'verifyAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];