/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AboutSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'featuredImage' : IDL.Opt(ExternalBlob),
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'school' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const Sponsor = IDL.Record({
  'id' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'organization' : IDL.Opt(IDL.Text),
});
export const PublicSiteSettings = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'heroBackground' : IDL.Opt(ExternalBlob),
});
export const SiteSettings = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'whatsappNumber' : IDL.Text,
  'heroBackground' : IDL.Opt(ExternalBlob),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAboutSection' : IDL.Func([AboutSection], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addContactSubmission' : IDL.Func([ContactSubmission], [], []),
  'addEvent' : IDL.Func([Event], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addSponsor' : IDL.Func([Sponsor], [], []),
  'addTeamMember' : IDL.Func([TeamMember], [], []),
  'addVideo' : IDL.Func([Video], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAboutSection' : IDL.Func([IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteContactSubmission' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
  'deleteSponsor' : IDL.Func([IDL.Text], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllAboutSections' : IDL.Func([], [IDL.Vec(AboutSection)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getPublicSiteSettings' : IDL.Func([], [PublicSiteSettings], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getWhatsAppLink' : IDL.Func([], [IDL.Text], ['query']),
  'isAdminConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAboutSection' : IDL.Func([AboutSection], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateEvent' : IDL.Func([Event], [], []),
  'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  'updateSponsor' : IDL.Func([Sponsor], [], []),
  'updateTeamMember' : IDL.Func([TeamMember], [], []),
  'updateVideo' : IDL.Func([Video], [], []),
  'verifyAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AboutSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'featuredImage' : IDL.Opt(ExternalBlob),
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'school' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Sponsor = IDL.Record({
    'id' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'organization' : IDL.Opt(IDL.Text),
  });
  const PublicSiteSettings = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'heroBackground' : IDL.Opt(ExternalBlob),
  });
  const SiteSettings = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'whatsappNumber' : IDL.Text,
    'heroBackground' : IDL.Opt(ExternalBlob),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAboutSection' : IDL.Func([AboutSection], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addContactSubmission' : IDL.Func([ContactSubmission], [], []),
    'addEvent' : IDL.Func([Event], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addSponsor' : IDL.Func([Sponsor], [], []),
    'addTeamMember' : IDL.Func([TeamMember], [], []),
    'addVideo' : IDL.Func([Video], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAboutSection' : IDL.Func([IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteContactSubmission' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
    'deleteSponsor' : IDL.Func([IDL.Text], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllAboutSections' : IDL.Func([], [IDL.Vec(AboutSection)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getPublicSiteSettings' : IDL.Func([], [PublicSiteSettings], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getWhatsAppLink' : IDL.Func([], [IDL.Text], ['query']),
    'isAdminConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAboutSection' : IDL.Func([AboutSection], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateEvent' : IDL.Func([Event], [], []),
    'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
    'updateSponsor' : IDL.Func([Sponsor], [], []),
    'updateTeamMember' : IDL.Func([TeamMember], [], []),
    'updateVideo' : IDL.Func([Video], [], []),
    'verifyAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };